apiVersion : apps/v1
kind: Deployment
metadata:
  name: "bdoexdevcluster04-034e"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "bdoexdevcluster04-034e"
  template:
    metadata:
      labels:
        app: "bdoexdevcluster04-034e"
    spec:
      containers:
        - name: "bdoexdevcluster04-034e"
          image: "bdoexdevacr02.azurecr.io/bdoexdevcluster04"
          ports:
          - containerPort: 80